spring.datasource.url=jdbc:mysql://localhost:3306/bonsai_shop?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Kha15122004!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.username=buinamkha2004@gmail.com
spring.mail.password=vvsj hsuf zwnn mjex

spring.security.oauth2.client.registration.google.client-id=177607764220-41r2d5cse7hqst701sh7qffgiagmbu23.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

