ALTER TABLE `review` 
ADD COLUMN IF NOT EXISTS `ReviewStatus` varchar(20) NOT NULL DEFAULT 'PENDING' AFTER `Comment`,
ADD COLUMN IF NOT EXISTS `Response` varchar(1000) DEFAULT NULL AFTER `ReviewStatus`;
