-- Migration V2: Add Product Journal Event and Media Tables

CREATE TABLE IF NOT EXISTS `PRODUCT_JOURNAL_EVENT` (
  `EventID` INT AUTO_INCREMENT PRIMARY KEY,
  `ProductID` INT NOT NULL,
  `CreatedByID` INT NULL,
  `EventDate` DATE NOT NULL,
  `EventType` VARCHAR(50) NOT NULL DEFAULT 'PHOTO_UPDATE',
  `Title` VARCHAR(255) NOT NULL,
  `Description` TEXT NULL,
  `IsPublic` TINYINT(1) DEFAULT 1,
  `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_pje_product` FOREIGN KEY (`ProductID`) REFERENCES `PRODUCT` (`ProductID`) ON DELETE CASCADE,
  CONSTRAINT `fk_pje_user` FOREIGN KEY (`CreatedByID`) REFERENCES `USER` (`UserID`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `PRODUCT_JOURNAL_MEDIA` (
  `MediaID` INT AUTO_INCREMENT PRIMARY KEY,
  `EventID` INT NOT NULL,
  `MediaURL` VARCHAR(500) NOT NULL,
  `MediaType` VARCHAR(50) NOT NULL DEFAULT 'IMAGE',
  `Caption` VARCHAR(255) NULL,
  `DisplayOrder` INT DEFAULT 0,
  CONSTRAINT `fk_pjm_event` FOREIGN KEY (`EventID`) REFERENCES `PRODUCT_JOURNAL_EVENT` (`EventID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;